### ISSUE TITLE
Getting textures to display correctly/closer to what the training preview shows

### ISSUE THREAD

**Issue by constantm** [NVlabs/nvdiffrec#100]
Hello! Firstly, this is awesome work and I've loved playing around with it so far. 

I've been generating synthetic datasets with Blender, using COLMAP to estimate camera poses from around 100 images, and then running it through nvdiffrec to get back a mesh + textures. The mesh output is pretty decent, however I'm having difficulty getting good textures. The textures look very washed out. If I look at the images being saved during training, the textures look pretty good. However, when I open the finished mesh, the textures look very washed out. Below I've attached a few crops to detail my issue:

1. Crop of input image in `img_mesh_pass_000100.png`:
<img width="209" alt="Screen Shot 2022-12-04 at 11 39 52 AM" src="https://user-images.githubusercontent.com/292439/205473144-64e6e42a-0ad3-4c64-b01f-82da2f3df496.png">

2. Crop of training preview in `img_mesh_pass_000100.png` - what I would expect the end result to look like:
<img width="174" alt="Screen Shot 2022-12-04 at 11 30 53 AM" src="https://user-images.githubusercontent.com/292439/205472978-de811615-457d-41cd-a6d5-f15ea52133b9.png">

3. Crop of mesh imported to Blender with normal and specular maps applied:
<img width="160" alt="Screen Shot 2022-12-04 at 11 44 44 AM" src="https://user-images.githubusercontent.com/292439/205473244-d24d1419-6920-487d-aa41-07f762619ef1.png">

4. The Blender node setup used:
<img width="488" alt="Screen Shot 2022-12-04 at 11 45 35 AM" src="https://user-images.githubusercontent.com/292439/205473278-2412b48b-fc92-45f0-ae6e-44911f3a7941.png">

5. Opening the generated mesh in Meshlab has the same washed-out look:
<img width="206" alt="Screen Shot 2022-12-04 at 11 50 44 AM" src="https://user-images.githubusercontent.com/292439/205473415-437030f6-2392-4ee6-8c39-6992de6b47c2.png">

I would expect the final output to look like the training previews (image 2), but I might be misunderstanding what the training previews actually are.

My config is as follows:

```json
{
    "ref_mesh" : "nerf_dataset",
    "random_textures": true,
    "iter": 5000,
    "save_interval": 100,
    "texture_res": [ 2048, 2048 ],
    "train_res": [800, 800],
    "batch": 8,
    "learning_rate": [0.03, 0.01],
    "mesh_scale" : 2.2,
    "dmtet_grid" : 128,
    "out_dir": "out",
    "background" : "white"
}
```

So, my questions are:
- What are the training previews? Is this actually a render of the mesh and texture in the current training state at that step, or something else?
- Do you have any pointers on how to improve the texture so it doesn't look as washed out?

Any input here would be greatly appreciated, thank you!

**Comment by constantm** [comment]
I got it working with the Blender script located in the Nvdiffrec Monte Carlo repo here: https://github.com/NVlabs/nvdiffrecmc/blob/main/blender/blender.py

**Comment by sadexcavator** [comment]
> I've been generating synthetic datasets with Blender, using COLMAP to estimate camera poses from around 100 images, and then running it through nvdiffrec to get back a mesh + textures. The mesh output is pretty decent, however I'm having difficulty getting good textures. The textures look very washed out. If I look at the images being saved during training, the textures look pretty good. However, when I open the finished me

hi, could you please give me some details about how to use the script 'blender.py' in Blender? I haven't use this software before,  and I got stuck here, thanks!

**Comment by constantm** [comment]
@sadexcavator it's pretty straight forward:

1. Open the `blender.py` script in Blender
2. Update the path in the script that points to the generated mesh
3. Run the script by clicking the Play button

The result should be a mesh in your workspace with shading nodes set up correctly.
