### ISSUE TITLE
cropped  output

### ISSUE THREAD

**Issue by derrick-xwp** [NVlabs/nvdiffrec#106]
I am using following configs:

> the dmtet_grid is 256
    
    "random_textures": true,
    "iter": 5000,
    "save_interval": 100,
    "texture_res": [ 2048, 2048 ],
    "train_res": [800, 800],
    "batch": 8,
    "learning_rate": [0.03, 0.01],
    "ks_min" : [0, 0.1, 0.0],
    "dmtet_grid" : 256,
    "mesh_scale" : 2.3,
    "laplace_scale" : 3000,
    "display": [{"latlong" : true}, {"bsdf" : "kd"}, {"bsdf" : "ks"}, {"bsdf" : "normal"}],
    "layers" : 4,
    "background" : "white",
    "out_dir": "nerf_drums_256"

The rendered image is cropped:
![img_dmtet_pass1_000001](https://user-images.githubusercontent.com/53371723/208440989-31e5e801-a31e-4b2c-9c1d-639bc773efec.png)

**Comment by jmunkberg** [comment]
Hello, 

I assume you generated the high resolution (256) grid yourself? My guess is that the scale or origin of the tet grid is different from the ones we shipped. I would recommend to print the bbox min/max value for a run using "dmtet_grid" : 128, and then verify that your generated 256 grid has the same extents.

**Comment by jmunkberg** [comment]
You can also look at early training images. The tet grid should be centered and tightly cover the object.

**Comment by derrick-xwp** [comment]
Thanks for your answer.
May I ask about the necessity of scale?
It just rescales the verts to be within [-0.5, 0.5] ?

**Comment by jmunkberg** [comment]
The tet grid spans the volume we optimize inside. Only inside that volume can we create geometry. 
The same extents are also used for volumetric texturing.
