### ISSUE TITLE
3D reconstruction metrics

### ISSUE THREAD

**Issue by iraj465** [NVlabs/nvdiffrec#114]
Hi,
In your paper there was mention of Chamfer distance, FLIP, LPIPS etc metrics
But in the code i only found PSNR and mse loss, can you please point me to that part of code? Need to evaluate the metrics in comparison

**Comment by jmunkberg** [comment]
FLIP: https://github.com/NVlabs/flip
LPIPS: https://github.com/richzhang/PerceptualSimilarity
Chamfer: https://kaolin.readthedocs.io/en/latest/modules/kaolin.metrics.pointcloud.html
