### ISSUE TITLE
build tiny-cuda-nn error

### ISSUE THREAD

**Issue by Holmes-Alan** [NVlabs/nvdiffrec#12]
Hello there, I have a problem compiling the tiny-cuda-nn. I compiled it on a win10 system with RTX3090, CUDA11.3 and VS2019. Somehow I just cannot compile the tiny-cuda-nn and I got too many errors that seem to come from VS. Can you help me out?
![image](https://user-images.githubusercontent.com/15608099/161173683-c54f90d9-c6af-4542-84bb-95cc04100f89.png)

**Comment by jmunkberg** [comment]
Hello, 

I haven't seen that issue locally. Note that we only use the encoder part of tcnn, `pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` 

Does it work if you compile the tiny-cuda-nn torch bindings in isolation, following?
https://github.com/NVlabs/tiny-cuda-nn#pytorch-extension

For tiny-cuda-nn issues, please report it directly at https://github.com/NVlabs/tiny-cuda-nn as we are just users of that separate project.

**Comment by JHnvidia** [comment]
Hi @Holmes-Alan,

Unfortunately there can be compability issues between MSVC versions and cuda versions. I've noted a similar error spam in the std headers if my MSVC version is too new for the CUDA version. Please try to upgrade to CUDA 11.6 developer kit and see if this goes away (make sure to reboot and check that the CUDA_PATH is updated to point to 11.6). 

It's possible to have a newer version of CUDA than used in pytorch, so locally I'm running with pytorch cuda = 11.3 and MSVC cuda = 11.6.

Best regards

**Comment by Holmes-Alan** [comment]
problem solved, Thank you!

**Comment by ECE-Engineer** [comment]
@Holmes-Alan may I please ask how you resolved the issue?

I have a very similar setup as to what you mentioned and I'm currently dealing with the same issue.
