### ISSUE TITLE
Dose DMTet support irregular tet grids?

### ISSUE THREAD

**Issue by fzy139** [NVlabs/nvdiffrec#132]
Hi,

Thanks for your excellent work. 

I wonder if the current DMTet implementation supports irregular tet grids, e.g. after subdivision of a subset of tets, so that it can produce more detailed geometry like the original DMTet paper shows.

Thanks

**Comment by jmunkberg** [comment]
Thanks, 

No, the current code base assumes a regular tet grid. As you suggest, it should be possible to experiment with both uniform and non-uniform subdivisions, following the DMTet paper, but that is not supported in the current code base. Feel free to explore it!

**Comment by frankshen07** [comment]
Hi @fzy139, MT cannot guarantee a watertight output with an irregular grid. In the original DMTet paper, we subdivide all surface tets (tets with different signs at the corners) and their one-ring neighbors. The unsubdivided cells are discarded, so the new grid remains "regular" in the sense that all cells have the same subdivision level. 
If you're planning to further optimize the SDF after subdivision, it's important to ensure there is no sign change at the grid boundary to avoid creating open surfaces. To achieve this, you can fix the SDF values at the grid boundary immediately after subdivision.

**Comment by fzy139** [comment]
Thanks! Very helpful. I'll have a try.
