### ISSUE TITLE
Add a how to cite! 

### ISSUE THREAD

**Issue by TontonTremblay** [NVlabs/nvdiffrec#143]
It would be useful :D

**Comment by JHnvidia** [comment]
Hi @TontonTremblay,

You can find a bibtex entry on the main project page: https://nvlabs.github.io/nvdiffrec/

**Comment by TontonTremblay** [comment]
Like I was telling Jacob yesterday. When you google search nvdiffrec you end up here, and there is no how to cite or even where it was publish. It would be a lot easier if the how to cite lived in both places.

**Comment by jmunkberg** [comment]
Thanks @TontonTremblay !

Fixed in [commit ](https://github.com/NVlabs/nvdiffrec/commit/dad3249af8ede96c7dd72c30328272117fabb710)
