### ISSUE TITLE
util.rotate_x seems inverse from gl's right hand rule

### ISSUE THREAD

**Issue by 2226415223** [NVlabs/nvdiffrec#152]
as mentioned above, is it a mistake from other diffrential project so you have to negtive all the x angle before pass to util.rotate_x,
the following is the correct matrix
![image](https://github.com/NVlabs/nvdiffrec/assets/62322001/d21ffd3d-9a3c-45a1-949d-77141254dddd)

**Comment by jmunkberg** [comment]
Thanks for highlighting this @2226415223 ! 

Yes, as you mention, this is an issue we inherited from nvdiffrast https://github.com/NVlabs/nvdiffrast/blob/main/samples/torch/util.py#L28

Fixed in CL [a3e7390](https://github.com/NVlabs/nvdiffrec/commit/a3e73909a01887c8a135235ff860dd23a045cc1b)
