### ISSUE TITLE
Use DMTet on udf. 

### ISSUE THREAD

**Issue by boqian-li** [NVlabs/nvdiffrec#153]
Hi, i wanna know if it's possible to use DMtet on udf field or non-water-tight mesh?

**Comment by jmunkberg** [comment]
Hello @ActonLee ,

We haven't tried with udf fields. Given that this is a DMTet question, not related to nvdiffrec, 
I would recommend to ask this question directly at https://github.com/NVIDIAGameWorks/kaolin

**Comment by boqian-li** [comment]
Thanks, I will.
