### ISSUE TITLE
Why rotate 90 degrees for camera poses in nerf-synthetic dataset?

### ISSUE THREAD

**Issue by Szy-Young** [NVlabs/nvdiffrec#163]
Hi! First very thanks for sharing this great work.

I am not clear why we need to rotate 90 degrees for camera poses in nerf-synthetic dataset, since Nvdiffrast adopts the same camera coordinate standard as Blender (which the nerf-synthetic dataset follows). According to my understanding, the camera poses provided in this dataset can be directly used without any processing.
https://github.com/NVlabs/nvdiffrec/blob/a3e73909a01887c8a135235ff860dd23a045cc1b/dataset/dataset_nerf.py#L67

Besides, I have also tried to run without this rotation in dataset loader, and it worked well. So is there any special reason for this rotation?

**Comment by jmunkberg** [comment]
Hello @Szy-Young 

IIRC, there is a difference between Blender's coordinate system and nvdiffrast (standard OpenGL). We added that rotation to account for that. It trains just fine without that rotation but the resulting object comes out rotated, which may be an issue if you want to load it back in Blender, with e.g., this script https://github.com/NVlabs/nvdiffrecmc?tab=readme-ov-file#use-the-extracted-3d-models-in-blender

**Comment by Szy-Young** [comment]
@jmunkberg Clearly got it. Thanks for the explanation!
