### ISSUE TITLE
how to perform training with our own dataset ? Will it produce same results with drone captured images ? 

### ISSUE THREAD

**Issue by piyushsingh2k7** [NVlabs/nvdiffrec#31]

**Comment by jmunkberg** [comment]
We need accurate camera poses and good foreground segmentation masks for high quality results. Avoid motion blur, defocus blur and changing lighting conditions (we assume a constant lighting and optimize a single environment map from the images). 

To prepare your own dataset, you can mostly follow https://github.com/bmild/nerf#generating-poses-for-your-own-scenes but please note that we need masks in the alpha channel.
