### ISSUE TITLE
How to run inference using custom images?

### ISSUE THREAD

**Issue by youssefavx** [NVlabs/nvdiffrec#33]
I'm really sorry if this has been asked before. 

1. Do I understand correctly that to run this you need a pretrained model or does it generate a 3D mesh from the training?
2. If it does need a pretrained model, is there a download link somewhere and example code on how to run inference on our own set of custom images?

I want to use this as a method to replace photogrammetry. So taking 100 pictures, or however many is needed of a real physical object, and running them through this model.

**Comment by youssefavx** [comment]
The example provided does not seem to take in a set of images to output a 3D mesh, instead it's a json config file with an hdr input and a obj file (what seems like an existing model?) So I assume what's going on inside is that there's a screenshot being taken of this mesh from a certain angle, then asking the model to reconstruct that mesh?

**Comment by jmunkberg** [comment]
Hello, 
Our method does not rely on a pre-trained model. Please see https://github.com/NVlabs/nvdiffrec/#datasets for a few examples of training with both synthetic images and real photos.  Example config: https://github.com/NVlabs/nvdiffrec/blob/main/configs/nerd_gold.json

We currently do not provide detailed instructions on how to run with your own images, but it has been discussed in other issues: https://github.com/NVlabs/nvdiffrec/issues/31
https://github.com/NVlabs/nvdiffrec/issues/26
https://github.com/NVlabs/nvdiffrec/issues/3
