### ISSUE TITLE
except blender

### ISSUE THREAD

**Issue by derrick-xwp** [NVlabs/nvdiffrec#43]
Dear author,

Except blender, are there other renderers that can render the output in interactive rate?

Thanks

**Comment by jmunkberg** [comment]
We output standard triangle meshes with textured PBR materials. The released code exports geometry as Wavefront .OBJ, which cam be opened and visualized at interactive rates in most 3D editing tools.
Materials a standard PBR materials, with a base color texture, a ORM map (roughness, specular) and a tangent space normal map.

An example on how to map the materials to Blender's PBR material is provided here https://github.com/NVlabs/nvdiffrec/issues/21 and it should be straightforward to do the same in other 3D tools.
