### ISSUE TITLE
surface subdivision

### ISSUE THREAD

**Issue by derrick-xwp** [NVlabs/nvdiffrec#44]
Dear author,
Is surface subdivision module released in this code or somewhere else?

Thanks

**Comment by jmunkberg** [comment]
Which surface subdivision are you referring to? 

We tried subdivision in a previous paper, and a simple version is included here
https://github.com/NVlabs/nvdiffmodeling/blob/main/src/mesh.py

There are also some DMTet https://nv-tlabs.github.io/DMTet/ examples in NVIDIA Kaolin https://github.com/NVIDIAGameWorks/kaolin

**Comment by frankshen07** [comment]
If you are referring to the surface subdivision module in DMTet, it is released in Kaolin: https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.mesh.html?highlight=subdivision#kaolin.ops.mesh.subdivide_trianglemesh
