### ISSUE TITLE
Trouble installing tinycudann

### ISSUE THREAD

**Issue by Askejm** [NVlabs/nvdiffrec#46]
Whenever i try running this command `pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` it spits out `ERROR: Command errored out with exit status 1`
![image](https://user-images.githubusercontent.com/55248977/172027279-c0f8d67a-2be9-4f25-b358-d73232f2dc2b.png)
I tried building it manually this way
![image](https://user-images.githubusercontent.com/55248977/172027287-90a7931d-c79c-4a7c-bb8c-47040c05ecc0.png)
but it just fails to build it then spits out the same error.
Tried the command below and get `RuntimeError: Error compiling objects for extension`
[fully_fused_mlp.cu.txt](https://github.com/NVlabs/nvdiffrec/files/8839033/fully_fused_mlp.cu.txt)
I also tried to cmake it, no luck 
![image](https://user-images.githubusercontent.com/55248977/172027376-15496da1-691c-4e1d-8c96-aa8142dd7288.png)

Cuda: 11.3
Python 3.9
Windows 10
CMake 3.23.2
Visual Studio 2019 community
Git 2.36.1
![image](https://user-images.githubusercontent.com/55248977/172027413-1024899a-daf4-440c-a03a-58d16ad4893b.png)
![image](https://user-images.githubusercontent.com/55248977/172027418-cc21769e-a5a3-4814-8e8d-92fc716be1f0.png)

**Comment by jmunkberg** [comment]
This seems to be an issue with tiny-cuda-nn, not the nvdiffrec code base. Please file an issue at https://github.com/NVlabs/tiny-cuda-nn as we do not control that code.
