### ISSUE TITLE
train.py not found

### ISSUE THREAD

**Issue by TheMeIonGod** [NVlabs/nvdiffrec#48]
After setting up with everything under Installation and doing all the One time setup commands after trying to do:
python train.py --config configs/bob.json
or
python train.py --config configs/bob.json --display-interval 20
I get this:
(dmodel) C:\WINDOWS\system32>python train.py --config configs/bob.json --display-interval 20
python: can't open file 'C:\WINDOWS\system32\train.py': [Errno 2] No such file or directory

I am sorry this might be a dumb question but I am stumped on how to fix it.

**Comment by jmunkberg** [comment]
You need to run the command `python train.py --config configs/bob.json --display-interval 20` in the folder where the code is located (the location where you cloned the repo).
