### ISSUE TITLE
Try to RUN in Ubuntu 20.04 raise this problem: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by arthurlirui** [NVlabs/nvdiffrec#55]
I pass previous  One time setup (Windows) step and try to run demo code, 

python train.py --config configs/bob.json
Config / Flags:
---------
config configs/bob.json
iter 1000
batch 4
spp 1
layers 1
train_res [512, 512]
display_res [512, 512]
texture_res [1024, 1024]
display_interval 0
save_interval 100
learning_rate [0.03, 0.003]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir out/bob
ref_mesh data/bob/bob_tri.obj
base_mesh None
validate False
mtl_override None
dmtet_grid 64
mesh_scale 2.1
env_scale 2.0
envmap data/irrmaps/aerodynamics_workshop_2k.hdr
display None
camera_space_light False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 10000.0
pre_load True
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.25, 0]
ks_max [1.0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
cam_near_far [0.1, 1000.0]
learn_light True
local_rank 0
multi_gpu True
---------
Traceback (most recent call last):
  File "/home/arthur/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/arthur/anaconda3/envs/dmodel/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

What is the reason for this error?

**Comment by arthurlirui** [comment]
Currently, I solve this problem by myself, the official setup is working on Windows, but if you want to run the code in Ubuntu, you actually need to replace opengl for Linux, that is `sudo apt-get install freeglut3-dev
Since glfw is Windows version opengl
`

**Comment by jmunkberg** [comment]
Thanks @arthurlirui ,

We rely on nvdiffrast for differentiable rasterization, which requires OpenGL. Here are details from their documentation: https://nvlabs.github.io/nvdiffrast/#linux

Our Dockerfile also handles the OpenGL setup, and includes the list of all required packages for nvdiffrast to work:  https://github.com/NVlabs/nvdiffrec/blob/main/docker/Dockerfile
