### ISSUE TITLE
How to run under linux ? 

### ISSUE THREAD

**Issue by Jiakui** [NVlabs/nvdiffrec#6]
Can you give a detailed instruction about how to run under linux ?

**Comment by jmunkberg** [comment]
The instructions in the readme for Windows should work unmodified also for Linux. Let us know if that is not the case. One known issue is that the ` --display-interval` flag doesn't work on Linux, so start your trainings like
```
python train.py --config configs/bob.json
```

You also have the option to run via docker (recommended when running on servers). Docker setup instructions at the end of the readme.
