### ISSUE TITLE
Jaggy geometry and texture details getting washed out

### ISSUE THREAD

**Issue by bsespede** [NVlabs/nvdiffrec#62]
Hello, first of all thanks for such a great work! I was briefly experimenting with the algorithm and I'm having some issues.

1) As you can see in the images the geometry looks very jaggy. I've created a higher res tet grid (256 - as big as my GPU would fit) but it seems to still have random "holes" and "spikes". Is there something I can do to prevent this? My scene has 108 frames and reconstruction results look very good on COLMAP.
2) Texture details seem washed out in comparison to the results in the paper. I thought it might be due to my extrinsics/intrinsics but they have rather low reproj error (~2pixels) so I'm really surprised (I've even extended the projection matrix to use different focal length and principal point per axis). Is there any setting I can tweak to improve this or insight why this might be happening? I've tried increasing iterations even further but it didnt help

![val_000107_normal](https://user-images.githubusercontent.com/11890419/179173804-c42ac955-c3de-4b10-a277-ba72e1f73d91.png)
![val_000107_opt](https://user-images.githubusercontent.com/11890419/179173810-7e3bc2f1-1c41-4100-8fcc-8723134373a3.png)
![val_000107_ref](https://user-images.githubusercontent.com/11890419/179173815-bdce896d-7183-43cd-bee9-ccde9e786246.png)

Kind regards,
Braulio

**Comment by JHnvidia** [comment]
Hi,

It's always quite tricky to pinpoint sources of quality drop. The main sources for geometric errors we've found are srtong speculars, inconsistent/varying lighting, and camera pose estimation. Unfortunately I'm not sure exactly how much error should be expacted at 2 px of reprojection error as we didn't focus much on camera poses.

It's possible to regularize (low pass filter) geometry through regularization, e.g. by using an MLP to encode the DMTet SDF. While we haven't released this code, a quick test could be to reduce the tet-grid resolution and see if the geometry improves a bit.

There's some additional information in this issue: https://github.com/NVlabs/nvdiffrec/issues/37

In recent follow up work we noted that it's sometimes beneficial with a normal smoothness loss (which can be implemented as a screen space loss term): https://arxiv.org/pdf/2206.03380.pdf

**Comment by tlok666** [comment]
> Hi,
> 
> It's always quite tricky to pinpoint sources of quality drop. The main sources for geometric errors we've found are srtong speculars, inconsistent/varying lighting, and camera pose estimation. Unfortunately I'm not sure exactly how much error should be expacted at 2 px of reprojection error as we didn't focus much on camera poses.
> 
> It's possible to regularize (low pass filter) geometry through regularization, e.g. by using an MLP to encode the DMTet SDF. While we haven't released this code, a quick test could be to reduce the tet-grid resolution and see if the geometry improves a bit.
> 
> There's some additional information in this issue: #37
> 
> In recent follow up work we noted that it's sometimes beneficial with a normal smoothness loss (which can be implemented as a screen space loss term): https://arxiv.org/pdf/2206.03380.pdf

Thanks for your advice.
Would you release code of the mentioned paper(https://arxiv.org/pdf/2206.03380.pdf)?
