### ISSUE TITLE
Generating meshes for entire scenes

### ISSUE THREAD

**Issue by CherniGhassen** [NVlabs/nvdiffrec#63]
Hi, 

Is it possible to generate meshes for an entire scene (i.e. a room)  by, for example, specifying a mask that encompasses the entirety of the scene? 

Thank you!

**Comment by JHnvidia** [comment]
Hi,

While technically possible, we did some very rough experiments convergence being a big issue. Consider a silhouette edge for example, it can be represented either through geometry or by texture inpainting. Without the silhouette term it tends to be easier for the system "cheat" through inpainting, which causes geometry to get stuck in a poor local minima.
