### ISSUE TITLE
Precomputed lighting code?

### ISSUE THREAD

**Issue by prashantraina** [NVlabs/nvdiffrec#66]
In the repo, there is a file called `data/irrmaps/bsdf_256_256.bin` which contains 2 precomputed lookup tables related to the lighting calculations. These tables are loaded as a variable called _FG_LUT in the code.
This is supposed to be related to the first integral in equation 5 of the paper. 
However, it is not obvious from the code how the integral and the 2 lookup tables are related to each other. 
Could you please share some details or code on how you precomputed `bsdf_256_256.bin`?

**Comment by jmunkberg** [comment]
See page 5-7 in this document: Real Shading in Unreal Engine 4

https://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf
