### ISSUE TITLE
How to show the nerf_lego dataset result in Blender properly

### ISSUE THREAD

**Issue by izumi-sss** [NVlabs/nvdiffrec#67]
First of all, thank you for your great work!

I want to show the result of nerf_lego mesh (/out/nerf_lego/mesh/mesh.obj) by Blender, but the output looks something wrong. (Image right)
It looks no problem img_mesh_pass_000X.png, and result of nerd_gold mesh looks no problem, too. (Image left)
![nerf_lego_bledner_result](https://user-images.githubusercontent.com/84551079/181452677-ba797bf9-48d3-40ed-b13f-a215cfed9531.png)
![img_mesh_pass_000030](https://user-images.githubusercontent.com/84551079/181455448-28be3f92-a64b-4848-9356-517e21195570.png)
I think the cause is in the loading settings on the Blender side, but I'm not familiar to Blender, so I would like to know how to display it correctly.

I'll show you the procedure how to import the result file by Blender, please point out if you see something wrong.
(The program configs have not been changed from the default ones.)
1. files -> import -> Wavefront (.obj)
2. Choose .obj file from /out/nerf_lego/mesh/mesh.obj. 

Thanks.

**Comment by jmunkberg** [comment]
An example on how to map the materials to Blender's PBR material is provided here https://github.com/NVlabs/nvdiffrec/issues/21 and it should be straightforward to do the same in other 3D tools.

**Comment by izumi-sss** [comment]
Thank you for quick reply!
#21 thread has helped me and I was able to map well. :)
