### ISSUE TITLE
How to adjust mesh_scale to custom object?

### ISSUE THREAD

**Issue by tlok666** [NVlabs/nvdiffrec#77]
Thanks for this interesting work. I reproduced the reconstruction by command: 'python train.py --config configs/bob.json'

But when I scale down to one-tenth the size of the original mesh(I have set the FLAGS.mesh_scale = 2.1/10.0), it does not work.

What should I do to obtain reconstructions from a smaller size object?

**Comment by jmunkberg** [comment]
The `mesh_scale` parameters determines the size of the tet-grid. If you scale it down while leaving everything else fixed, you will only reconstruct geometry in a smaller volume within that smaller grid.

For a smaller object, I recommend to move the camera closer to capture more detail. Best results are obtained when the object cover most of the screen.

**Comment by tlok666** [comment]
> The `mesh_scale` parameters determines the size of the tet-grid. If you scale it down while leaving everything else fixed, you will only reconstruct geometry in a smaller volume within that smaller grid.
> 
> For a smaller object, I recommend to move the camera closer to capture more detail. Best results are obtained when the object covers most of the screen.

Thanks for your reply. 
I use the same example to accomplish experiment. The 'bob_tri.obj' is down to one-tenth of the original mesh size. And the RADIUS is set to 3.0/6.0 in 'train.py'. 
The rendered image obtained the object, but no work for reconstruction.

**Comment by jmunkberg** [comment]
I tried to reproduce your issue locally:

1. Scaled down the model a factor 10
2. Moved the camera closer  (`RADIUS = 0.5` in train.py)
3. Added `"mesh_scale" : 0.21,` to the config

This is the result I am getting. It seems to work.

![img_dmtet_pass1_000000](https://user-images.githubusercontent.com/68556069/191022143-17a24b48-bc34-4040-a7cc-6e6696687aaf.png)

![img_dmtet_pass1_000010](https://user-images.githubusercontent.com/68556069/191022167-3e51aa48-dff4-4bc8-9286-9bebd44868c5.png)


Note that the near plane is set to 0.1 per default (`FLAGS.cam_near_far        = [0.1, 1000.0]`), so for very small scales, you may need to adjust that.

**Comment by tlok666** [comment]
> 1. n the mod

That is the something I come across. Thanks for your tips.
Best.

**Comment by tlok666** [comment]
> I tried to reproduce your issue locally:
> 
> 1. Scaled down the model a factor 10
> 2. Moved the camera closer  (`RADIUS = 0.5` in train.py)
> 3. Added `"mesh_scale" : 0.21,` to the config
> 
> This is the result I am getting. It seems to work.
> 
> ![img_dmtet_pass1_000000](https://user-images.githubusercontent.com/68556069/191022143-17a24b48-bc34-4040-a7cc-6e6696687aaf.png)
> 
> ![img_dmtet_pass1_000010](https://user-images.githubusercontent.com/68556069/191022167-3e51aa48-dff4-4bc8-9286-9bebd44868c5.png)
> 
> Note that the near plane is set to 0.1 per default (`FLAGS.cam_near_far = [0.1, 1000.0]`), so for very small scales, you may need to adjust that.

That is the something I come across. Thanks for your tips.
Best.
