### ISSUE TITLE
Is there anyway to resume training just for the texture?

### ISSUE THREAD

**Issue by Holorei** [NVlabs/nvdiffrec#78]
Hi and Thanks for your hardwork!
After receiving the DMTET mesh optimization and first validation result, the process went out of memory in GPU for texture training, knowing that a parameter in the config file wasn't modified.  I'm wondering if there is a way to resume training just for texture optimization.

**Comment by jmunkberg** [comment]
Thanks @Holorei ,

Yes, you can just run the second pass. For an example, please refer to the config https://github.com/NVlabs/nvdiffrec/blob/main/configs/spot_metal.json

Add the result from the first pass (available in the `dmtet_mesh` folder) as `base_mesh` and `envmap`, and start the optimization

Optionally, you can also use the `"lock_pos" : true` / `"lock_light" : true`, option to disable geometry/light optimization if you are only interested in tweaking texture quality.
