### ISSUE TITLE
How to show mesh with textures?

### ISSUE THREAD

**Issue by Doraemon167** [NVlabs/nvdiffrec#8]
Thank you for the amazing work! Now, I have trained the Nerf datasets of chair and I get a great result. I want to show the mesh with texture in MeshLab, but the chair mesh has nontexture in MeshLab. So what method should I use?
![1](https://user-images.githubusercontent.com/18532460/160581336-68c85a08-759d-453b-b75a-08c1f5575429.png)

**Comment by jmunkberg** [comment]
Thanks! 
We use a pbr shading model, and I'm not sure that is supported in Meshlab. If you want to just apply the diffuse texture, you could likely try Filters -> Texture -> Set Texture -> Texture file (load mesh/texture_kd.png).

However, that would not directly match the setup in our renderer, where we use kd, ks and a tangent space normal map. You can, e.g., load the mesh in Blender (or any tool of your choice supporting PBR) and map the three textures.

**Comment by Doraemon167** [comment]
Thank you jmunkberg! I solve this problem by Blender, it has a great result!

**Comment by fahimsun** [comment]
@Doraemon167 Can you please share your setup or instruction where KD/KS and (n) normal file will apply to which node? if you can provide picture of your node setup in blender that would be great.

**Comment by Doraemon167** [comment]
@fahimsun sorry,I'm not very good at using bleder,when I load the mesh, I can see the texture.

**Comment by jmunkberg** [comment]
@fahimsun See example here https://github.com/NVlabs/nvdiffrec/issues/21
