### ISSUE TITLE
Compile each time it runs?

### ISSUE THREAD

**Issue by carlosedubarreto** [NVlabs/nvdiffrec#82]
Hello and thansk for such amazing code.

I noticed that everytime that I run nvdiffrec it compiles some files.
Is that really needed?
Or can i disable it in some way?

I saw that some pyd gets in appdata (torch_extension folder) is created. If I point to that file I could skip the compiling everytime I run the script?

thanks a lot for you time

**Comment by JHnvidia** [comment]
Hi @carlosedubarreto,

The compilation is handled by pytorch/ninja and a compiled version should be in the `torch_extension` folder. It should only recompile if a file is changed. When we're using docker, the user folder is usually wiped on each docker instance, which causes recompiles, you may be experiencing something similar.

**Comment by carlosedubarreto** [comment]
Thanks a lot for the explanation

**Comment by carlosedubarreto** [comment]
I found that to make it work without trying to recompile (which gives me error when debugging) I can disable the `torch.utils.cpp_extension.load` and add a path to a place I have the files compiled.
![image](https://user-images.githubusercontent.com/4061130/195838389-d0f63cca-369c-4207-bfb9-a54d21075c06.png)

It worked fine with me.

I made those changes on 
C:\<path>\dmodel\Lib\site-packages\nvdiffrast\torch\ops.py
and 
D:\nvdiffrec\render\renderutils\ops.py

made a folder with these files
![image](https://user-images.githubusercontent.com/4061130/195838812-3d16dc08-0473-43ca-9b4c-2dfa2dca03ce.png)
