### ISSUE TITLE
Rendering quality depends too much on foreground masks quality 

### ISSUE THREAD

**Issue by iraj465** [NVlabs/nvdiffrec#86]
Hi,
Great work on the paper! Really good stuff. I was able to get some mid level quality results on my own datasets using rembg alpha channels. I was looking for manual NERD based masking to get better results. Not upto much good. Can you please provide any code which you have used in your paper with Detectron2 etc for generating masks? I see your results to be really good, might be that the masks' quality played a good role. Any leads is appreciated

**Comment by jmunkberg** [comment]
Thanks @iraj465 ,

For the mask tests in the supplemental, we used two versions of Detectron2, namely PointRend and Mask R-CNN. 
We used the code from the Detectron 2 github repo: https://github.com/facebookresearch/detectron2

This service also worked quite well in some tests: https://www.remove.bg/

Good masks definitely helps our reconstructions.

**Comment by iraj465** [comment]
Gotcha, thanks for this!
