### ISSUE TITLE
I cannot install pytorch extension on windows

### ISSUE THREAD

**Issue by silver-obelisk** [NVlabs/nvdiffrec#92]
Like a lot of other question,when I try to install pytorch extension on windows i meet many problems,but when i try to find answer on issues,there is no same to my problem.

`(ngp_pl) D:\tcnn\tiny-cuda-nn\bindings\torch>python setup.py install
Building PyTorch extension for tiny-cuda-nn version 1.6
Obtained compute capability 86 from PyTorch
running install
D:\Anaconda3\envs\ngp_pl\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\Anaconda3\envs\ngp_pl\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing tinycudann.egg-info\PKG-INFO
writing dependency_links to tinycudann.egg-info\dependency_links.txt
writing top-level names to tinycudann.egg-info\top_level.txt
reading manifest file 'tinycudann.egg-info\SOURCES.txt'
writing manifest file 'tinycudann.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building 'tinycudann_bindings_86._C' extension
D:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\tcnn\tiny-cuda-nn/include -ID:\tcnn\tiny-cuda-nn/dependencies -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/include -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/tools/util/include -ID:\tcnn\tiny-cuda-nn/dependencies/fmt/include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda3\envs\ngp_pl\include -ID:\Anaconda3\envs\ngp_pl\Include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\include "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tp../../dependencies/fmt/src/format.cc /Fobuild\temp.win32-cpython-38\Release\../../dependencies/fmt/src/format.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /std:c++14 -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
format.cc
D:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\tcnn\tiny-cuda-nn/include -ID:\tcnn\tiny-cuda-nn/dependencies -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/include -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/tools/util/include -ID:\tcnn\tiny-cuda-nn/dependencies/fmt/include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda3\envs\ngp_pl\include -ID:\Anaconda3\envs\ngp_pl\Include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\include "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tp../../dependencies/fmt/src/os.cc /Fobuild\temp.win32-cpython-38\Release\../../dependencies/fmt/src/os.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /std:c++14 -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
os.cc
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc" -c ../../src/common.cu -o build\temp.win32-cpython-38\Release\../../src/common.obj -ID:\tcnn\tiny-cuda-nn/include -ID:\tcnn\tiny-cuda-nn/dependencies -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/include -ID:\tcnn\tiny-cuda-nn/dependencies/cutlass/tools/util/include -ID:\tcnn\tiny-cuda-nn/dependencies/fmt/include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\ngp_pl\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda3\envs\ngp_pl\include -ID:\Anaconda3\envs\ngp_pl\Include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\Visual_Studio2019\Visual_Studio2019\VC\Tools\MSVC\14.29.30133\include "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -DTCNN_MIN_GPU_ARCH=86 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 --use-local-env
common.cu
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF2_OPERATORS__”(用“/U__CUDA_NO_HALF2_OPERATORS__”)
common.cu
D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime.h(197): error: invalid redeclaration of type name "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(48): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(53): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(59): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(64): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(166): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new.h(181): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new_debug.h(26): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_new_debug.h(34): error: first parameter of allocation function must be of type "size_t"

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(399): error: class template "std::_Is_memfunptr" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1676): error: class template "std::result_of" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1676): error: class template "std::result_of" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Visual_Studio2019/Visual_Studio2019/VC/Tools/MSVC/14.29.30133/include\type_traits(1776): error: class template "std::_Function_args" has already been defined

D:/Windows Kits/10/include/10.0.19041.0/ucrt\malloc.h(55): error: more than one instance of overloaded function "_alloca" has "C" linkage

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\crt/common_functions.h(125): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\crt/common_functions.h(126): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\crt/common_functions.h(263): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\crt/common_functions.h(264): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(124): error: cannot overload functions distinguished by return type alone

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(125): error: cannot overload functions distinguished by return type alone

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(126): error: cannot overload functions distinguished by return type alone

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(127): error: cannot overload functions distinguished by return type alone

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(128): warning: declaration overloads built-in function "__nv_cvta_global_to_generic_impl"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(128): error: more than one instance of overloaded function "__nv_cvta_global_to_generic_impl" has "C" linkage

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(129): warning: declaration overloads built-in function "__nv_cvta_shared_to_generic_impl"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(129): error: more than one instance of overloaded function "__nv_cvta_shared_to_generic_impl" has "C" linkage

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(130): warning: declaration overloads built-in function "__nv_cvta_constant_to_generic_impl"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(130): error: more than one instance of overloaded function "__nv_cvta_constant_to_generic_impl" has "C" linkage

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(131): warning: declaration overloads built-in function "__nv_cvta_local_to_generic_impl"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_20_intrinsics.hpp(131): error: more than one instance of overloaded function "__nv_cvta_local_to_generic_impl" has "C" linkage

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(104): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(105): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(109): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(110): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(111): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(112): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(113): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(114): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(115): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(116): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(117): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(118): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(119): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(120): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(122): error: asm operand type size(8) does not match type/size implied by constraint 'r'

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\sm_32_intrinsics.hpp(123): error: asm operand type size(8) does not match type/size implied by constraint 'r'

Error limit reached.
100 errors detected in the compilation of "../../src/common.cu".
Compilation terminated.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit code 1

`

just like you see,i stop on compilation of common.cu.
I used windows 10, 
python3.8,
torch-1.12.1+cu113 torchaudio-0.12.1+cu113 torchvision-0.13.1+cu113
msvc 2019 16.9.4

and also tried msvc 2019 16.11.16  ,cuda11.6 with corresponding pytorch，but all of them didnot work.

I must say the adaptation on windows is so trobule. Hope NVIDIA do some test and give some specific environment configuration.
And if someone have the way to slove this problem,please write here,thank you.

**Comment by jmunkberg** [comment]
Hello, 
This is a problem when installing tiny-cuda-nn, not our code, so please file an issue there: https://github.com/NVlabs/tiny-cuda-nn, or check if there is a recommended solution.
