### ISSUE TITLE
low quality reconstruction

### ISSUE THREAD

**Issue by sky23249** [NVlabs/nvdiffrec#93]
Hello, thanks for your great work! 
I follow the readme and execute command `python train.py --config configs/nerf_lego.json `, but the output looks not good, how can I improve the quality of the mesh?
![image](https://user-images.githubusercontent.com/103924094/201854978-dad0efb9-080c-4ef2-9bfe-9bfc3a39c18c.png)

Looking forward to your reply!

**Comment by jmunkberg** [comment]
Thanks! Please see issue https://github.com/NVlabs/nvdiffrec/issues/42
