### ISSUE TITLE
Do we support loading obj data from shapenet?

### ISSUE THREAD

**Issue by Zyq-scut** [NVlabs/nvdiffrec#98]
Hi, I try to load obj data from shapenet dataset via method "load_obj". However, the render result seem something wrong happened. Is this a bug or is just shapenet data not supported? Here are the render result and the ground truth.
![image](https://user-images.githubusercontent.com/66082575/203939568-c5e58e02-e52b-4f78-83d4-f0b5c21a7871.png)
![image](https://user-images.githubusercontent.com/66082575/203939875-2cd8226e-0dfe-4695-8bca-404ec49c33b7.png)
Could you give me some advice to fix it? Thanks a lot.

**Comment by Zyq-scut** [comment]
I have solved it!

**Comment by D1noFuzi** [comment]
@Zyq-scut how did you solve it?

**Comment by Zyq-scut** [comment]
> @Zyq-scut how did you solve it? I am facing similar problems as ShapeNet has multiple texture files per model. The renderer constantly fails to render it properly.
Hi @D1noFuzi . The official implement of `load_mlt` does not support the form of shapenet. So I rewrite this method to load .mlt file.

**Comment by wzking09** [comment]
> > @Zyq-scut how did you solve it? I am facing similar problems as ShapeNet has multiple texture files per model. The renderer constantly fails to render it properly.
> 
> Hi @D1noFuzi . The official implement of `load_mlt` does not support the form of shapenet. So I rewrite this method to load .mlt file.

Hi, can you share more details about 'load_mtl()' func? I tried to clip 'vt' to 0-1. Some of render results looks better and others not.
