### ISSUE TITLE
holes on metal spot

### ISSUE THREAD

**Issue by Zyq-scut** [NVlabs/nvdiffrec#99]
Hi, thanks for your excellent work. 
I try to generate metal spot without base mesh. However, there are many 'holes' on the result mesh. Is it too hard for the network to fix? How can I get a smooth mesh for the metal object? 
![image](https://user-images.githubusercontent.com/66082575/205275119-87e898ef-2797-4f52-9ffd-2f13a66c6a04.png)

**Comment by jmunkberg** [comment]
Hello @Zyq-scut ,

Joint optimizing of shape, materials, and lighting for highly specular objects is quite challenging. The smoothness regularizer here https://github.com/NVlabs/nvdiffrecmc/blob/main/geometry/dmtet.py#L240 may help somewhat (the term that penalizes differences in normal gradients).
